version: '3'

services:
  rag-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-system
    volumes:
      - ./data:/app/data
      - ./vector_db:/app/vector_db
      - ./logs:/app/logs
      - ./static:/app/static
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - LANGCHAIN_TRACING_V2=false
      - PORT=5000
    ports:
      - "5000:5000"
    command: bash -c "python src/ingest.py && python src/api.py"
    restart: unless-stopped 